WINDOWS_NAME = "nt"

SHORT_TIMEOUT, MEDIUM_TIMEOUT, LONG_TIMEOUT = 2, 6, 12

FIRST_LINE_INDEX, FIRST_ELEMENT_INDEX, SECOND_ELEMENT_INDEX = 0, 0, 1

ONE_LINE, TWO_LINES = 1, 2

EMPTY_BYTES_LINE, NEW_LINE = b'', '\n'

HEXADECIMAL_BASE = 16
